{% raw %}
##
# Db installation and creation
##
---
    - name: install necessary packages
      become: true
      become_method: sudo
      apt:
        state: present
        update_cache: yes
        name:
          - libpq-dev
          - postgresql-client
    - name: Install psycopg2 python package
      pip:
        name: psycopg2
{% endraw %}
