{% raw %}
##
# Db installation and creation
##
---
    - name: install necessary packages
      become: true
      become_method: sudo
      apt:
        state: present
        update_cache: yes
        name:
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - postgresql-client
          - postgresql-client-common

    - name: Install psycopg2 python package
      pip:
        name: psycopg2

    - name: Create the db user
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        encrypted: True
        state: "present"
      become: true
      become_user: postgres
      notify: restart db service

    - name: create the db
      postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        template: template0
        encoding: UTF8
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'
      become: true
      become_user: postgres
      notify: restart db service
{% endraw %}
