# Generated by Django 5.0.3 on 2024-07-01 10:00

import django.db.models.deletion
import subject_imagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContentMultiAttachment',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('use_accordion', models.BooleanField(default=False, help_text='set to true if you want this block to be inside an accordion, the block name will be used inside the accordion head')),
            ],
            options={
                'verbose_name': 'attachment content block',
                'verbose_name_plural': 'attachment content blocks',
            },
            bases=('pages.pagecontent', models.Model),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cabinet.folder', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
                'ordering': ['name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', subject_imagefield.fields.SubjectImageField(blank=True, max_length=1000, subject_location_field='subject_location', upload_to='cabinet/%Y/%m', verbose_name='immagine')),
                ('subject_location', models.CharField(default='50,50', max_length=7, verbose_name='coordinate soggetto')),
                ('image_width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='larghezza')),
                ('image_height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='altezza')),
                ('image_alt_text', models.CharField(blank=True, max_length=1000, verbose_name='testo alternativo')),
                ('download_file', models.FileField(blank=True, help_text='You can upload a file to download or an image, not both', max_length=1000, upload_to='cabinet/%Y/%m', verbose_name='file')),
                ('download_type', models.CharField(editable=False, max_length=20, verbose_name='download type')),
                ('_overwrite', models.BooleanField(default=False, help_text='By default, a new and unique filename is generated for each file, which also helps with caching.', verbose_name='Keep filename this time when uploading new file?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('file_name', models.CharField(max_length=1000, verbose_name='nome file')),
                ('file_size', models.PositiveIntegerField(verbose_name='dimensioni')),
                ('caption', models.CharField(blank=True, max_length=1000, verbose_name='caption')),
                ('copyright', models.CharField(blank=True, max_length=1000, verbose_name='copyright')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='cabinet.folder', verbose_name='folder')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'ordering': ['file_name'],
                'abstract': False,
                'swappable': 'CABINET_FILE_MODEL',
            },
        ),
        migrations.CreateModel(
            name='AttachmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrizione')),
                ('position', models.IntegerField(default=0, verbose_name='ordinamento')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.CABINET_FILE_MODEL, verbose_name='file')),
                ('page_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cabinet.pagecontentmultiattachment', verbose_name='contenuto')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'file',
                'ordering': ('position',),
            },
        ),
    ]
