# Generated by Django 4.1.2 on 2023-08-02 08:24

from django.db import migrations, models
import subject_imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_auto_20190415_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='image_ppoi',
        ),
        migrations.AddField(
            model_name='file',
            name='subject_location',
            field=models.CharField(default='50,50', max_length=7, verbose_name='coordinate soggetto'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=1000, verbose_name='nome file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.PositiveIntegerField(verbose_name='dimensioni'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='testo alternativo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image_file',
            field=subject_imagefield.fields.SubjectImageField(blank=True, max_length=1000, subject_location_field='subject_location', upload_to='cabinet/%Y/%m', verbose_name='immagine'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='altezza'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='larghezza'),
        ),
    ]
