# Generated by Django 4.1.2 on 2023-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_remove_file_image_ppoi_file_subject_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='download_file',
            field=models.FileField(blank=True, help_text='You can upload a file to download or an image, not both', max_length=1000, upload_to='cabinet/%Y/%m', verbose_name='file'),
        ),
    ]
