# Generated by Django 4.1.2 on 2024-01-17 01:46

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0047_alter_pagecontentboxitem_file_and_more"),
        ("cabinet", "0007_alter_file_download_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContentAttachment",
            fields=[
                (
                    "pagecontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.pagecontent",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="cabinet.folder",
                        verbose_name="folder",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.CABINET_FILE_MODEL,
                        verbose_name="file",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("file", "File"), ("folder", "Folder")],
                        default="file",
                        max_length=6,
                        verbose_name="choose attachment type",
                    ),
                ),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="description"
                    ),
                ),
                (
                    "description_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_fr",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_it",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment content block",
                "verbose_name_plural": "attachment content blocks",
            },
            bases=("pages.pagecontent",),
        ),
    ]
