# Generated by Django 4.1.2 on 2024-03-06 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0057_rename_content_map_pagecontentmapitem_block"),
        ("cabinet", "0008_pagecontentattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContentMultiAttachment",
            fields=[
                (
                    "pagecontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.pagecontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment content block",
                "verbose_name_plural": "attachment content blocks",
            },
            bases=("pages.pagecontent",),
        ),
        migrations.CreateModel(
            name="AttachmentModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(default=0, verbose_name="ordinamento"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "name_it",
                    models.CharField(max_length=200, null=True, verbose_name="nome"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, null=True, verbose_name="nome"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=200, null=True, verbose_name="nome"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.CABINET_FILE_MODEL,
                        verbose_name="file",
                    ),
                ),
                (
                    "page_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="cabinet.pagecontentmultiattachment",
                        verbose_name="contenuto",
                    ),
                ),
            ],
            options={
                "verbose_name": "file",
                "verbose_name_plural": "file",
                "ordering": ("position",),
            },
        ),
    ]
