# Generated by Django 4.1.2 on 2024-03-06 11:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cabinet", "0009_pagecontentmultiattachment_attachmentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontentmultiattachment",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="description"
            ),
        ),
    ]
