# Generated by Django 4.1.2 on 2024-03-06 13:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cabinet", "0010_pagecontentmultiattachment_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagecontentattachment",
            options={
                "verbose_name": "old attachment content block",
                "verbose_name_plural": "old attachment content blocks",
            },
        ),
        migrations.RemoveField(
            model_name="pagecontentmultiattachment",
            name="description",
        ),
        migrations.AddField(
            model_name="attachmentmodel",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="description"
            ),
        ),
    ]
