# Generated by Django 4.1.2 on 2024-03-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cabinet", "0011_alter_pagecontentattachment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentmodel",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="descrizione"),
        ),
    ]
