# Generated by Django 4.1.2 on 2024-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cabinet", "0012_alter_attachmentmodel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachmentmodel",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="descrizione"),
        ),
        migrations.AddField(
            model_name="attachmentmodel",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="descrizione"),
        ),
        migrations.AddField(
            model_name="attachmentmodel",
            name="description_it",
            field=models.TextField(blank=True, null=True, verbose_name="descrizione"),
        ),
    ]
