# Generated by Django 5.0.3 on 2024-04-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0013_attachmentmodel_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='description_it',
        ),
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='name_it',
        ),
        migrations.DeleteModel(
            name='PageContentAttachment',
        ),
    ]
