# Generated by Django 5.0.3 on 2024-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_remove_attachmentmodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='descrizione'),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='descrizione'),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='descrizione'),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='name_it',
            field=models.CharField(max_length=200, null=True, verbose_name='nome'),
        ),
    ]
