# Generated by Django 5.0.3 on 2024-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0015_attachmentmodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentmodel',
            name='use_accordion',
            field=models.BooleanField(default=False, help_text='set to true if you want this block to be inside an accordion, the block name will be used inside the accordion head'),
        ),
    ]
