# Generated by Django 5.0.3 on 2024-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0016_attachmentmodel_use_accordion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='use_accordion',
        ),
        migrations.AddField(
            model_name='pagecontentmultiattachment',
            name='use_accordion',
            field=models.BooleanField(default=False, help_text='set to true if you want this block to be inside an accordion, the block name will be used inside the accordion head'),
        ),
    ]
