FROM ubuntu:{{ cookiecutter.ubuntu_version }}

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ={{ cookiecutter.timezone }}

RUN apt-get update && \
    apt-get install -y \
        ansible \
        python3 \
	    locales \
        openssh-client \
        postgresql-client \
        git

RUN localedef -f UTF-8 -i en_US en_US.utf8

ENV NVM_DIR=/usr/local/nvm
RUN mkdir -p $NVM_DIR
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
ENV NODE_VERSION=v20.6.1
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION"
RUN /bin/bash -c "ln -s $NVM_DIR/versions/node/$NODE_VERSION/bin/node /usr/bin/node"
RUN /bin/bash -c "ln -s $NVM_DIR/versions/node/$NODE_VERSION/lib/node_modules/npm/bin/npm-cli.js /usr/bin/npm"

COPY . ./home/app/{{cookiecutter.repo_name}}
WORKDIR /home/app/{{cookiecutter.repo_name}}

RUN ./bin/ansible_local

RUN mkdir /root/.ssh && chmod 0700 /root/.ssh

# --- INSTRUCTIONS ---
# Uncomment the following line ONLY WHEN your domain is live and reachable via SSH.
# This command adds your server's SSH key to the container, which is useful for
# automated deployments or other SSH operations.
# For now, it is left commented out to allow the initial build to succeed even without a live server.
#
# RUN ssh-keyscan {{cookiecutter.domain}} >> ~/.ssh/known_hosts

RUN apt-get -y install gettext


