FROM python:3.12-slim-bookworm

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ={{ cookiecutter.timezone }}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
        libjpeg-dev \
        zlib1g-dev \
        libffi-dev \
        libssl-dev \
        gettext \
        locales \
        postgresql-client \
        git \
        wget \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN localedef -f UTF-8 -i en_US en_US.utf8

ENV NVM_DIR=/usr/local/nvm
RUN mkdir -p $NVM_DIR
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
ENV NODE_VERSION=v20.6.1
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION"
RUN /bin/bash -c "ln -s $NVM_DIR/versions/node/$NODE_VERSION/bin/node /usr/bin/node"
RUN /bin/bash -c "ln -s $NVM_DIR/versions/node/$NODE_VERSION/lib/node_modules/npm/bin/npm-cli.js /usr/bin/npm"

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN python -m venv "$VIRTUAL_ENV"
COPY {{cookiecutter.repo_name}}/requirements /tmp/requirements
RUN pip install --no-cache-dir -r /tmp/requirements/local.txt

WORKDIR /home/app/{{cookiecutter.repo_name}}
