# Generated by Django 5.0.3 on 2024-11-13 09:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_models', models.JSONField(default=core.models.ai_models_default, verbose_name='ai models')),
                ('hide_archived', models.BooleanField(default=False, verbose_name='nascondi archiviati')),
                ('robots', models.TextField(blank=True, default='', verbose_name='robots')),
                ('site_title', models.CharField(blank=True, default='evalux-api', max_length=100, verbose_name='titolo sito')),
                ('meta_title', models.CharField(blank=True, default='evalux-api', max_length=100, verbose_name='titolo meta')),
                ('meta_description', models.CharField(blank=True, default='Evalux API', max_length=300, verbose_name='descrizione meta')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='preferences/', verbose_name='immagine meta')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='parole chiave meta')),
            ],
            options={
                'verbose_name': 'preferenze',
                'verbose_name_plural': 'preferenze',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
