# Generated by Django 5.0.3 on 2024-07-01 10:00

import ckeditor_uploader.fields
import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import subject_imagefield.fields
import taggit_autosuggest.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome')),
                ('show_name', models.BooleanField(default=False, verbose_name='show name')),
                ('background_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#D0E8F3', 'blue'), ('#AADAC5', 'green'), ('#F0E8DB', 'beige'), ('#DCD5C8', 'brown')], verbose_name='background color')),
                ('object_id', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('position', models.IntegerField(editable=False, verbose_name='ordering')),
                ('enabled', models.BooleanField(default=True, verbose_name='block enabled')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='titolo')),
                ('template_name', models.CharField(blank=True, help_text="Esempio: 'flatpages/contact_page.html'. Se non specificato, il sistema userà 'flatpages/default.html'.", max_length=70, verbose_name='nome template')),
                ('registration_required', models.BooleanField(default=False, help_text="Se selezionato, solo gli utenti che hanno effettuato l'accesso potranno vedere la pagina.", verbose_name='registrazione obbligatoria')),
                ('enable_social_sharing', models.BooleanField(default=False, verbose_name='abilita condivisione social')),
                ('last_updated', models.BooleanField(default=True, help_text='show last updated date', verbose_name='last updated')),
                ('status', models.IntegerField(choices=[(1, 'bozza'), (2, 'pubblicato'), (3, 'archiviato')], default=1)),
                ('relevance', models.IntegerField(choices=[(1, 'alta'), (2, 'media'), (3, 'bassa')], default=2, help_text='priority level for searches', verbose_name='rilevanza')),
                ('meta_title', models.CharField(blank=True, help_text='default: titolo pagina', max_length=200, null=True, verbose_name='titolo meta tag')),
                ('meta_description', models.TextField(blank=True, help_text='default: prime 20 parole del contenuto', null=True, verbose_name='descrizione meta tag')),
                ('meta_keywords', models.CharField(blank=True, help_text='default: tag', max_length=200, null=True, verbose_name='parole chiave meta tag')),
                ('groups', models.ManyToManyField(blank=True, help_text='If registration is required and groups are filled, than only users belonging to these groups can access the content.', related_name='pages', to='auth.group', verbose_name='gruppi')),
                ('parent', models.ForeignKey(blank=True, help_text='Usato per comporre le briciole di pane', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page', verbose_name='genitore')),
                ('sites', models.ManyToManyField(to='sites.site', verbose_name='siti')),
                ('tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tag')),
                ('users', models.ManyToManyField(blank=True, help_text='If registration is required and users are filled, than only this users can access the content.', related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='utenti')),
            ],
            options={
                'verbose_name': 'pagina',
                'verbose_name_plural': 'pagine',
                'ordering': ('url',),
            },
        ),
        migrations.CreateModel(
            name='PageContentBoxMenu',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('columns', models.IntegerField(default=5, help_text='maximum number of boxes per row', verbose_name='columns')),
                ('shadow', models.BooleanField(default=True, help_text='set to true if you want the boxes to have a shadow on name and icon', verbose_name='shadow')),
                ('zoom', models.BooleanField(default=False, help_text='set to true if you want the boxes to zoom on hover', verbose_name='zoom')),
                ('rounding', models.IntegerField(default=8, help_text='set the rounding of the boxes in pixels', verbose_name='rounding')),
                ('rectangular', models.BooleanField(default=False, help_text='set to true if you want boxes to become rectangular when they are stretched', verbose_name='rectangular')),
            ],
            options={
                'verbose_name': 'Box menu',
                'verbose_name_plural': 'Box menus',
            },
            bases=('pages.pagecontent',),
        ),
        migrations.CreateModel(
            name='PageContentImage',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('image_content', models.ImageField(upload_to='pages/image_content', verbose_name='contenuto')),
                ('show_captions', models.BooleanField(default=True, help_text='set to true if you want to show the captions of the images', verbose_name='show captions')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='didascalia')),
                ('credits', models.TextField(blank=True, null=True, verbose_name='credits')),
                ('url', models.CharField(blank=True, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'image content block',
                'verbose_name_plural': 'image content blocks',
            },
            bases=('pages.pagecontent',),
        ),
        migrations.CreateModel(
            name='PageContentMap',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='contenuto')),
                ('height', models.IntegerField(default=400, verbose_name='height (px)')),
            ],
            options={
                'verbose_name': 'map content block',
                'verbose_name_plural': 'map content blocks',
            },
            bases=('pages.pagecontent',),
        ),
        migrations.CreateModel(
            name='PageContentMultiImage',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('type', models.CharField(choices=[('carousel', 'Carousel'), ('grid', 'Grid')], default='carousel', max_length=20, verbose_name='choose representation type')),
                ('show_captions', models.BooleanField(default=True, help_text='set to true if you want to show the captions of the images', verbose_name='show captions')),
                ('height', models.IntegerField(default=450, help_text='set the max height of the carousel images in pixels', verbose_name='carousel max height')),
            ],
            options={
                'verbose_name': 'multi image content block',
                'verbose_name_plural': 'multi image content blocks',
            },
            bases=('pages.pagecontent',),
        ),
        migrations.CreateModel(
            name='PageContentRssFeed',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('rss_feed_url', models.URLField(verbose_name='rss feed url')),
                ('num_items', models.IntegerField(default=5, verbose_name='number of items')),
            ],
            options={
                'verbose_name': 'RSS feed block',
                'verbose_name_plural': 'RSS feed blocks',
            },
            bases=('pages.pagecontent',),
        ),
        migrations.CreateModel(
            name='PageContentText',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('use_accordion', models.BooleanField(default=False, help_text='set to true if you want this block to be inside an accordion, the block name will be used inside the accordion head')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='contenuto')),
                ('url', models.CharField(blank=True, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'text content block',
                'verbose_name_plural': 'text content blocks',
            },
            bases=('pages.pagecontent', models.Model),
        ),
        migrations.CreateModel(
            name='PageContentTextImage',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('use_accordion', models.BooleanField(default=False, help_text='set to true if you want this block to be inside an accordion, the block name will be used inside the accordion head')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='text')),
                ('left_column_width', models.IntegerField(blank=True, default=50, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='left column width (%)')),
                ('image', models.ImageField(upload_to='pages/text_image_content', verbose_name='image')),
                ('image_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=5, verbose_name='image position')),
                ('show_captions', models.BooleanField(default=True, help_text='set to true if you want to show the captions of the images', verbose_name='show captions')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='didascalia')),
                ('credits', models.TextField(blank=True, null=True, verbose_name='credits')),
            ],
            options={
                'verbose_name': 'text and image content block',
                'verbose_name_plural': 'text and image content blocks',
            },
            bases=('pages.pagecontent', models.Model),
        ),
        migrations.CreateModel(
            name='PageContentVideo',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='descrizione')),
                ('credits', models.TextField(blank=True, null=True, verbose_name='credits')),
                ('platform', models.IntegerField(choices=[(1, 'Youtube'), (2, 'Vimeo'), (3, 'Twitch')], default=1, verbose_name='platform')),
                ('video_id', models.CharField(max_length=255, verbose_name='video id')),
                ('width_percent', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='width percent')),
            ],
            options={
                'verbose_name': 'Video block',
                'verbose_name_plural': 'Video blocks',
            },
            bases=('pages.pagecontent',),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='pages.page'),
        ),
        migrations.CreateModel(
            name='PageContentBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', subject_imagefield.fields.SubjectImageField(blank=True, null=True, subject_location_field='subject_location', upload_to='pages/box_menu_content', verbose_name='image')),
                ('subject_location', models.CharField(default='50,50', max_length=7, verbose_name='subject coordinates')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='nome')),
                ('link', models.CharField(max_length=200, verbose_name='url')),
                ('icon', models.FileField(blank=True, help_text='upload an svg icon', null=True, upload_to='park-life/', verbose_name='icon')),
                ('position', models.IntegerField(default=0, verbose_name='order')),
                ('text_color', models.CharField(default='#f5f5f5', help_text='set the color of box name', max_length=7, verbose_name='text color')),
                ('bg_color', models.CharField(default='#f5f5f5', help_text='set the color of box background', max_length=7, verbose_name='background color')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.pagecontentboxmenu')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='PageContentMapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('POINT', 'Point'), ('POLYLINE', 'Polyline'), ('POLYGON', 'Polygon'), ('CIRCLE', 'Circle')], default='POINT', max_length=16)),
                ('coordinates', models.TextField(verbose_name='coordinates')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='didascalia')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='color')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.pagecontentmap')),
            ],
            options={
                'verbose_name': 'Map item',
                'verbose_name_plural': 'Map items',
            },
        ),
        migrations.CreateModel(
            name='PageContentMultiImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', subject_imagefield.fields.SubjectImageField(subject_location_field='subject_location', upload_to='pages/multi_image_content', verbose_name='file')),
                ('subject_location', models.CharField(default='50,50', max_length=7, verbose_name='subject coordinates')),
                ('position', models.IntegerField(default=0, verbose_name='order')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='didascalia')),
                ('credits', models.TextField(blank=True, null=True, verbose_name='credits')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.pagecontentmultiimage')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ('position',),
            },
        ),
    ]
