# Generated by Django 5.2.1 on 2025-06-11 07:28

import baton.fields
import ckeditor_uploader.fields
import colorfield.fields
import django.db.models.deletion
import taggit_autosuggest.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('url',), 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AddField(
            model_name='pagecontentimage',
            name='image_subject_location',
            field=models.CharField(default='50,50', max_length=7),
        ),
        migrations.AlterField(
            model_name='page',
            name='enable_social_sharing',
            field=models.BooleanField(default=False, verbose_name='enable social sharing'),
        ),
        migrations.AlterField(
            model_name='page',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='If registration is required and groups are filled, than only users belonging to these groups can access the content.', related_name='pages', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, help_text='default to first 20 words of content', null=True, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='default to page tags', max_length=200, null=True, verbose_name='meta keywords'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='default to page title', max_length=200, null=True, verbose_name='meta title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Used to compose breadcrumbs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='page',
            name='registration_required',
            field=models.BooleanField(default=False, help_text='If this is checked, only logged-in users will be able to view the page.', verbose_name='registration required'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sites',
            field=models.ManyToManyField(to='sites.site', verbose_name='sites'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subject_location',
            field=models.CharField(default='50,50', max_length=7),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_name',
            field=models.CharField(blank=True, help_text="Example: 'pages/contact_page.html'. If this isn't provided, the system will use 'pages/default.html'.", max_length=70, verbose_name='template name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='If registration is required and users are filled, than only this users can access the content.', related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pagecontentboxitem',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#084cbf', 'blue'), ('#0ea20c', 'green'), ('#e20716', 'red'), ('#ba1cab', 'purple'), ('#f5c828', 'yellow'), ('#38a9ca', 'cyan')], verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='pagecontentboxitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pagecontentimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontentimage',
            name='image_content',
            field=baton.fields.BatonAiImageField(alt_chars=20, alt_field='caption', alt_language='en-us', subject_location_field='image_subject_location', upload_to='pages/image_content', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='pagecontentmap',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='pagecontentmapitem',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='pagecontentmapitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pagecontentmultiimageitem',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='pagecontenttext',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='pagecontenttextimage',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='pagecontentvideo',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='description'),
        ),
    ]
