# Generated by Django 5.2.1 on 2025-06-11 07:41

import baton.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontenttextimage',
            name='image',
            field=baton.fields.BatonAiImageField(alt_chars=20, alt_field='caption', alt_language='en-us', subject_location_field='subject_location', upload_to='pages/text_image_content', verbose_name='image'),
        ),
    ]
