# Generated by Django 4.1.2 on 2023-09-27 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_alter_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.AddField(
            model_name='page',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='If registration is required and groups are filled, than only users belonging to these groups can access the content.', related_name='pages', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='page',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='If registration is required and users are filled, than only this users can access the content.', related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
