# Generated by Django 5.2.1 on 2025-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_pagecontenttextimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontenttextimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
