# Generated by Django 5.2.1 on 2025-06-11 07:50

import baton.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pagecontenttextimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontentmultiimageitem',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='pagecontentmultiimageitem',
            name='file',
            field=baton.fields.BatonAiImageField(alt_chars=20, alt_field='caption', alt_language='en-us', subject_location_field='subject_location', upload_to='pages/multi_image_content', verbose_name='file'),
        ),
    ]
