# Generated by Django 5.2.1 on 2025-06-11 07:56

import baton.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_pagecontentmultiimageitem_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontentboxitem',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt text'),
        ),
        migrations.AlterField(
            model_name='pagecontentboxitem',
            name='file',
            field=baton.fields.BatonAiImageField(alt_chars=20, alt_field='alt_text', alt_language='en-us', blank=True, null=True, subject_location_field='subject_location', upload_to='pages/box_menu_content', verbose_name='image'),
        ),
    ]
