# Generated by Django 4.1.2 on 2023-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pagecontent_pagecontenttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
