# Generated by Django 4.1.2 on 2023-09-27 13:37

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('sites', '0002_alter_domain_unique'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pages', '0006_alter_pagecontent_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('url',), 'verbose_name': 'pagina', 'verbose_name_plural': 'pagine'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='pagecontenttext',
            options={'verbose_name': 'text content block', 'verbose_name_plural': 'text content blocks'},
        ),
        migrations.AlterField(
            model_name='page',
            name='enable_social_sharing',
            field=models.BooleanField(default=False, verbose_name='abilita condivisione social'),
        ),
        migrations.AlterField(
            model_name='page',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='If registration is required and groups are filled, than only users belonging to these groups can access the content.', related_name='pages', to='auth.group', verbose_name='gruppi'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, help_text='default: prime 20 parole del contenuto', null=True, verbose_name='descrizione meta tag'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='default: tag', max_length=200, null=True, verbose_name='parole chiave meta tag'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='default: titolo pagina', max_length=200, null=True, verbose_name='titolo meta tag'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Usato per comporre le briciole di pane', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page', verbose_name='genitore'),
        ),
        migrations.AlterField(
            model_name='page',
            name='registration_required',
            field=models.BooleanField(default=False, help_text="Se selezionato, solo gli utenti che hanno effettuato l'accesso potranno vedere la pagina.", verbose_name='registrazione obbligatoria'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sites',
            field=models.ManyToManyField(to='sites.site', verbose_name='siti'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='valori separati da virgola', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_name',
            field=models.CharField(blank=True, help_text="Esempio: 'flatpages/contact_page.html'. Se non specificato, il sistema userà 'flatpages/default.html'.", max_length=70, verbose_name='nome template'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titolo'),
        ),
        migrations.AlterField(
            model_name='page',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='If registration is required and users are filled, than only this users can access the content.', related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='utenti'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='position',
            field=models.IntegerField(editable=False, verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='pagecontenttext',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='contenuto'),
        ),
    ]
