# Generated by Django 4.1.2 on 2023-10-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_page_options_alter_pagecontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nome'),
        ),
    ]
