# Generated by Django 4.1.2 on 2023-10-10 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_pagecontent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContentImage',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('content', models.ImageField(upload_to='', verbose_name='contenuto')),
            ],
            options={
                'verbose_name': 'image content block',
                'verbose_name_plural': 'image content blocks',
            },
            bases=('pages.pagecontent',),
        ),
    ]
