# Generated by Django 4.1.2 on 2023-10-10 00:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_pagecontentimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContentTextImage",
            fields=[
                (
                    "pagecontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.pagecontent",
                    ),
                ),
                (
                    "text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="text"
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="image")),
                (
                    "image_position",
                    models.CharField(
                        choices=[("left", "left"), ("right", "right")],
                        default="right",
                        max_length=5,
                        verbose_name="image position",
                    ),
                ),
            ],
            options={
                "verbose_name": "text and image content block",
                "verbose_name_plural": "text and image content blocks",
            },
            bases=("pages.pagecontent",),
        ),
    ]
