# Generated by Django 4.1.2 on 2023-10-20 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.CABINET_FILE_MODEL),
        ("pages", "0010_pagecontenttextimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontenttextimage",
            name="image_position",
            field=models.CharField(
                choices=[("left", "Left"), ("right", "Right")],
                default="right",
                max_length=5,
                verbose_name="image position",
            ),
        ),
        migrations.CreateModel(
            name="PageContentAttachment",
            fields=[
                (
                    "pagecontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.pagecontent",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.CABINET_FILE_MODEL,
                        verbose_name="attachment",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment content block",
                "verbose_name_plural": "attachment content blocks",
            },
            bases=("pages.pagecontent",),
        ),
    ]
