# Generated by Django 4.1.2 on 2023-10-20 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.CABINET_FILE_MODEL),
        ("cabinet", "0007_alter_file_download_file"),
        ("pages", "0011_alter_pagecontenttextimage_image_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontentattachment",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="cabinet.folder",
                verbose_name="cartella",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentattachment",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.CABINET_FILE_MODEL,
                verbose_name="attachment",
            ),
        ),
    ]
