# Generated by Django 4.1.2 on 2023-10-20 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.CABINET_FILE_MODEL),
        ("pages", "0012_pagecontentattachment_folder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecontentattachment",
            name="attachment",
        ),
        migrations.AddField(
            model_name="pagecontentattachment",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.CABINET_FILE_MODEL,
                verbose_name="file",
            ),
        ),
        migrations.AddField(
            model_name="pagecontentattachment",
            name="type",
            field=models.CharField(
                choices=[("file", "File"), ("folder", "Folder")],
                default="file",
                max_length=6,
                verbose_name="type",
            ),
        ),
    ]
