# Generated by Django 4.1.2 on 2023-10-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_remove_pagecontentattachment_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontentattachment",
            name="type",
            field=models.CharField(
                choices=[("file", "File"), ("folder", "Folder")],
                default="file",
                max_length=6,
                verbose_name="choose attachment type",
            ),
        ),
    ]
