# Generated by Django 4.1.2 on 2023-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0014_alter_pagecontentattachment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="show_name",
            field=models.BooleanField(default=False, verbose_name="show name"),
        ),
        migrations.AddField(
            model_name="pagecontentattachment",
            name="description",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="descrizione"
            ),
        ),
    ]
