# Generated by Django 4.1.2 on 2023-10-24 13:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0015_pagecontent_show_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontentattachment",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="", verbose_name="descrizione"
            ),
            preserve_default=False,
        ),
    ]
