# Generated by Django 4.1.2 on 2023-10-24 13:34

from django.db import migrations, models
import django.db.models.deletion
import subject_imagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0016_alter_pagecontentattachment_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContentMultiImage",
            fields=[
                (
                    "pagecontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.pagecontent",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("carousel", "Carousel")],
                        default="carousel",
                        max_length=20,
                        verbose_name="choose representation type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="descrizione"),
                ),
            ],
            options={
                "verbose_name": "multi image content block",
                "verbose_name_plural": "multi image content blocks",
            },
            bases=("pages.pagecontent",),
        ),
        migrations.CreateModel(
            name="PageContentMultiImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    subject_imagefield.fields.SubjectImageField(
                        subject_location_field="subject_location",
                        upload_to="model_images/",
                        verbose_name="file",
                    ),
                ),
                (
                    "subject_location",
                    models.CharField(
                        default="50,50",
                        max_length=7,
                        verbose_name="coordinate soggetto",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(default=0, verbose_name="ordinamento"),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="didascalia"),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pages.pagecontentmultiimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "immagine",
                "verbose_name_plural": "immagini",
                "ordering": ("position",),
                "abstract": False,
            },
        ),
    ]
