# Generated by Django 4.1.2 on 2023-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_pagecontentmultiimage_pagecontentmultiimageitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecontentmultiimage",
            name="description",
        ),
        migrations.AlterField(
            model_name="pagecontentmultiimage",
            name="type",
            field=models.CharField(
                choices=[("carousel", "Carousel"), ("grid", "Grid")],
                default="carousel",
                max_length=20,
                verbose_name="choose representation type",
            ),
        ),
    ]
