# Generated by Django 4.1.2 on 2023-10-26 17:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0018_remove_pagecontentmultiimage_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=[
                    ("#45A4D2", "blue"),
                    ("#55B68C", "green"),
                    ("#C9AC7D", "beige"),
                    ("#BAAB91", "brown"),
                ],
                verbose_name="background color",
            ),
        ),
    ]
