# Generated by Django 4.1.2 on 2023-10-26 18:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0019_pagecontent_background_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontent",
            name="background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=[
                    ("#D0E8F3", "blue"),
                    ("#AADAC5", "green"),
                    ("#F0E8DB", "beige"),
                    ("#DCD5C8", "brown"),
                ],
                verbose_name="background color",
            ),
        ),
    ]
