# Generated by Django 4.1.2 on 2023-10-26 18:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0020_alter_pagecontent_background_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="nome"
            ),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="nome"
            ),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="name_it",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="nome"
            ),
        ),
        migrations.AddField(
            model_name="pagecontentattachment",
            name="description_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="descrizione"
            ),
        ),
        migrations.AddField(
            model_name="pagecontentattachment",
            name="description_fr",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="descrizione"
            ),
        ),
        migrations.AddField(
            model_name="pagecontentattachment",
            name="description_it",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="descrizione"
            ),
        ),
        migrations.AddField(
            model_name="pagecontenttext",
            name="content_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="contenuto"
            ),
        ),
        migrations.AddField(
            model_name="pagecontenttext",
            name="content_fr",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="contenuto"
            ),
        ),
        migrations.AddField(
            model_name="pagecontenttext",
            name="content_it",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="contenuto"
            ),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="text_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="text"
            ),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="text_fr",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="text"
            ),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="text_it",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="text"
            ),
        ),
    ]
