# Generated by Django 4.1.2 on 2023-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0021_pagecontent_name_en_pagecontent_name_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontentmultiimageitem",
            name="caption_en",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentmultiimageitem",
            name="caption_fr",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentmultiimageitem",
            name="caption_it",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
    ]
