# Generated by Django 4.1.2 on 2023-11-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0022_pagecontentmultiimageitem_caption_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontentmultiimageitem",
            name="link",
            field=models.URLField(blank=True, verbose_name="link"),
        ),
    ]
