# Generated by Django 4.1.2 on 2023-11-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0023_pagecontentmultiimageitem_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="left_column_width",
            field=models.IntegerField(
                blank=True, default=50, null=True, verbose_name="left column width"
            ),
        ),
    ]
