# Generated by Django 4.1.2 on 2023-11-07 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0024_pagecontenttextimage_left_column_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontent",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="block enabled"),
        ),
        migrations.AlterField(
            model_name="pagecontenttextimage",
            name="left_column_width",
            field=models.IntegerField(
                blank=True,
                default=50,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="left column width",
            ),
        ),
    ]
