# Generated by Django 4.1.2 on 2023-11-08 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0025_alter_pagecontent_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontenttextimage",
            name="left_column_width",
            field=models.IntegerField(
                blank=True,
                default=50,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="left column width (%)",
            ),
        ),
    ]
