# Generated by Django 4.1.2 on 2023-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0026_alter_pagecontenttextimage_left_column_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontentmultiimageitem",
            name="credits",
            field=models.TextField(blank=True, null=True, verbose_name="crediti"),
        ),
    ]
