# Generated by Django 4.1.2 on 2023-12-13 11:05

from django.db import migrations, models
import django.db.models.deletion
import subject_imagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0027_pagecontentmultiimageitem_credits"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContentBoxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    subject_imagefield.fields.SubjectImageField(
                        subject_location_field="subject_location",
                        upload_to="page_images/",
                        verbose_name="immagine",
                    ),
                ),
                (
                    "subject_location",
                    models.CharField(
                        default="50,50",
                        max_length=7,
                        verbose_name="coordinate soggetto",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                ("link", models.CharField(max_length=200, verbose_name="url")),
                (
                    "icon",
                    models.FileField(
                        help_text="campo per il caricamento di icone in svg",
                        upload_to="park-life/",
                        verbose_name="icona",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(default=0, verbose_name="ordinamento"),
                ),
            ],
            options={
                "verbose_name": "Box",
                "verbose_name_plural": "Box",
            },
        ),
        migrations.CreateModel(
            name="PageContentBoxMenu",
            fields=[
                (
                    "pagecontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.pagecontent",
                    ),
                ),
                (
                    "columns",
                    models.IntegerField(
                        default=5,
                        help_text="Numero massimo di box per riga",
                        verbose_name="colonne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Box menu",
                "verbose_name_plural": "Box menu",
            },
            bases=("pages.pagecontent",),
        ),
    ]
