# Generated by Django 4.1.2 on 2023-12-13 13:07

from django.db import migrations, models
import django.db.models.deletion
import subject_imagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0028_pagecontentboxitem_pagecontentboxmenu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagecontentboxitem",
            options={"verbose_name": "Box", "verbose_name_plural": "Boxes"},
        ),
        migrations.AlterModelOptions(
            name="pagecontentboxmenu",
            options={"verbose_name": "Box menu", "verbose_name_plural": "Box menus"},
        ),
        migrations.AlterModelOptions(
            name="pagecontentmultiimageitem",
            options={
                "ordering": ("position",),
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="block",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="pages.pagecontentboxmenu",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="nome"),
        ),
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="name_fr",
            field=models.CharField(max_length=100, null=True, verbose_name="nome"),
        ),
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="name_it",
            field=models.CharField(max_length=100, null=True, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="file",
            field=subject_imagefield.fields.SubjectImageField(
                subject_location_field="subject_location",
                upload_to="page_images/",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="icon",
            field=models.FileField(
                help_text="upload an svg icon",
                upload_to="park-life/",
                verbose_name="icon",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="position",
            field=models.IntegerField(default=0, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="subject_location",
            field=models.CharField(
                default="50,50", max_length=7, verbose_name="subject coordinates"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxmenu",
            name="columns",
            field=models.IntegerField(
                default=5,
                help_text="maximum number of boxes per row",
                verbose_name="columns",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentmultiimageitem",
            name="credits",
            field=models.TextField(blank=True, null=True, verbose_name="credits"),
        ),
        migrations.AlterField(
            model_name="pagecontentmultiimageitem",
            name="position",
            field=models.IntegerField(default=0, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="pagecontentmultiimageitem",
            name="subject_location",
            field=models.CharField(
                default="50,50", max_length=7, verbose_name="subject coordinates"
            ),
        ),
    ]
