# Generated by Django 4.1.2 on 2023-12-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0029_alter_pagecontentboxitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontentboxmenu",
            name="rectangular",
            field=models.BooleanField(
                default=False,
                help_text="set to true if you want boxes to become rectangular when they are stretched",
                verbose_name="rectangular",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="nome"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="nome"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="name_it",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="nome"
            ),
        ),
    ]
