# Generated by Django 4.1.2 on 2024-01-03 14:36

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("pages", "0030_pagecontentboxmenu_rectangular_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="tags",
            field=taggit_autosuggest.managers.TaggableManager(
                blank=True,
                help_text="valori separati da virgola",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="tag",
            ),
        ),
    ]
