# Generated by Django 4.1.2 on 2024-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0031_alter_page_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="titolo"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_fr",
            field=models.CharField(max_length=200, null=True, verbose_name="titolo"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_it",
            field=models.CharField(max_length=200, null=True, verbose_name="titolo"),
        ),
    ]
