# Generated by Django 4.1.2 on 2024-01-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0034_pagecontent_created_pagecontent_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="last_updated",
            field=models.BooleanField(
                default=True,
                help_text="show last updated date",
                verbose_name="last updated",
            ),
        ),
        migrations.AddField(
            model_name="pagecontentboxmenu",
            name="color",
            field=models.CharField(
                default="#f5f5f5",
                help_text="set the color of name and icon",
                max_length=7,
                verbose_name="color",
            ),
        ),
        migrations.AddField(
            model_name="pagecontentboxmenu",
            name="rounding",
            field=models.CharField(
                default="0",
                help_text="set the rounding of the boxes",
                max_length=7,
                verbose_name="rounding",
            ),
        ),
        migrations.AddField(
            model_name="pagecontentboxmenu",
            name="shadow",
            field=models.BooleanField(
                default=False,
                help_text="set to true if you want the boxes to have a shadow on name and icon",
                verbose_name="shadow",
            ),
        ),
        migrations.AddField(
            model_name="pagecontentboxmenu",
            name="zoom",
            field=models.BooleanField(
                default=False,
                help_text="set to true if you want the boxes to zoom on hover",
                verbose_name="zoom",
            ),
        ),
    ]
