# Generated by Django 4.1.2 on 2024-01-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0035_page_last_updated_pagecontentboxmenu_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontentboxmenu",
            name="rounding",
            field=models.IntegerField(
                default="8",
                help_text="set the rounding of the boxes in pixels",
                max_length=7,
                verbose_name="rounding",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxmenu",
            name="shadow",
            field=models.BooleanField(
                default=True,
                help_text="set to true if you want the boxes to have a shadow on name and icon",
                verbose_name="shadow",
            ),
        ),
    ]
