# Generated by Django 4.1.2 on 2024-01-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0036_alter_pagecontentboxmenu_rounding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontentboxmenu",
            name="rounding",
            field=models.IntegerField(
                default=8,
                help_text="set the rounding of the boxes in pixels",
                verbose_name="rounding",
            ),
        ),
    ]
