# Generated by Django 4.1.2 on 2024-01-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0037_alter_pagecontentboxmenu_rounding"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContentRssFeed",
            fields=[
                (
                    "pagecontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.pagecontent",
                    ),
                ),
                ("rss_feed_url", models.URLField(verbose_name="rss feed url")),
                (
                    "num_items",
                    models.IntegerField(default=5, verbose_name="number of items"),
                ),
            ],
            options={
                "verbose_name": "RSS feed block",
                "verbose_name_plural": "RSS feed blocks",
            },
            bases=("pages.pagecontent",),
        ),
        migrations.AlterField(
            model_name="pagecontentboxmenu",
            name="color",
            field=models.CharField(
                default="#f5f5f5",
                help_text="set the color of box name",
                max_length=7,
                verbose_name="color",
            ),
        ),
    ]
