# Generated by Django 4.1.2 on 2024-01-09 07:59

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0038_pagecontentrssfeed_alter_pagecontentboxmenu_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContentMap",
            fields=[
                (
                    "pagecontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.pagecontent",
                    ),
                ),
                (
                    "text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="contenuto"
                    ),
                ),
            ],
            options={
                "verbose_name": "map content block",
                "verbose_name_plural": "map content blocks",
            },
            bases=("pages.pagecontent",),
        ),
        migrations.CreateModel(
            name="PageContentMapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("POINT", "Point"),
                            ("POLYLINE", "Polyline"),
                            ("POLYGON", "Polygon"),
                            ("CIRCLE", "Circle"),
                        ],
                        default="POINT",
                        max_length=16,
                    ),
                ),
                ("coordinates", models.TextField(verbose_name="coordinates")),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="didascalia"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="link"
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#000000",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="color",
                    ),
                ),
                (
                    "content_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pages.pagecontentmap",
                    ),
                ),
            ],
        ),
    ]
