# Generated by Django 4.1.2 on 2024-01-09 08:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0039_pagecontentmap_pagecontentmapitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontentmap",
            name="text_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="contenuto"
            ),
        ),
        migrations.AddField(
            model_name="pagecontentmap",
            name="text_fr",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="contenuto"
            ),
        ),
        migrations.AddField(
            model_name="pagecontentmap",
            name="text_it",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="contenuto"
            ),
        ),
        migrations.AddField(
            model_name="pagecontentmapitem",
            name="caption_en",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentmapitem",
            name="caption_fr",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentmapitem",
            name="caption_it",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentmapitem",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="nome"),
        ),
        migrations.AddField(
            model_name="pagecontentmapitem",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="nome"),
        ),
        migrations.AddField(
            model_name="pagecontentmapitem",
            name="name_it",
            field=models.CharField(max_length=255, null=True, verbose_name="nome"),
        ),
    ]
