# Generated by Django 4.1.2 on 2024-01-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0040_pagecontentmap_text_en_pagecontentmap_text_fr_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagecontentmapitem",
            options={"verbose_name": "Map item", "verbose_name_plural": "Map items"},
        ),
        migrations.AddField(
            model_name="pagecontentmap",
            name="height",
            field=models.IntegerField(default=400, verbose_name="height (px)"),
        ),
    ]
