# Generated by Django 4.1.2 on 2024-01-16 10:46

from django.db import migrations, models
import subject_imagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0041_alter_pagecontentmapitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecontentboxmenu",
            name="color",
        ),
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="bg_color",
            field=models.CharField(
                blank=True,
                default="#f5f5f5",
                help_text="set the color of box background",
                max_length=7,
                null=True,
                verbose_name="color",
            ),
        ),
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="text_color",
            field=models.CharField(
                default="#f5f5f5",
                help_text="set the color of box name",
                max_length=7,
                verbose_name="color",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="file",
            field=subject_imagefield.fields.SubjectImageField(
                blank=True,
                null=True,
                subject_location_field="subject_location",
                upload_to="page_images/",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="upload an svg icon",
                null=True,
                upload_to="park-life/",
                verbose_name="icon",
            ),
        ),
    ]
