# Generated by Django 4.1.2 on 2024-01-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0042_remove_pagecontentboxmenu_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="bg_color",
            field=models.CharField(
                default="#f5f5f5",
                help_text="set the color of box background",
                max_length=7,
                verbose_name="background color",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="text_color",
            field=models.CharField(
                default="#f5f5f5",
                help_text="set the color of box name",
                max_length=7,
                verbose_name="text color",
            ),
        ),
    ]
