# Generated by Django 4.1.2 on 2024-01-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0043_alter_pagecontentboxitem_bg_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontenttext",
            name="use_accordion",
            field=models.BooleanField(
                default=False,
                help_text="set to true if you want this block to be inside an accordion, the name will be used inside the accordion head",
            ),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="use_accordion",
            field=models.BooleanField(
                default=False,
                help_text="set to true if you want this block to be inside an accordion, the name will be used inside the accordion head",
            ),
        ),
    ]
