# Generated by Django 4.1.2 on 2024-01-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0044_pagecontenttext_use_accordion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontenttext",
            name="use_accordion",
            field=models.BooleanField(
                default=False,
                help_text="set to true if you want this block to be inside an accordion, the block name will be used inside the accordion head",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontenttextimage",
            name="use_accordion",
            field=models.BooleanField(
                default=False,
                help_text="set to true if you want this block to be inside an accordion, the block name will be used inside the accordion head",
            ),
        ),
    ]
