# Generated by Django 4.1.2 on 2024-01-16 17:15

from django.db import migrations, models
import subject_imagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0045_alter_pagecontenttext_use_accordion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="file",
            field=subject_imagefield.fields.SubjectImageField(
                blank=True,
                null=True,
                subject_location_field="subject_location",
                upload_to="pages/box_content",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentimage",
            name="content",
            field=models.ImageField(
                upload_to="pages/image_content", verbose_name="contenuto"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontentmultiimageitem",
            name="file",
            field=subject_imagefield.fields.SubjectImageField(
                subject_location_field="subject_location",
                upload_to="pages/multi_image_content",
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="pagecontenttextimage",
            name="image",
            field=models.ImageField(
                upload_to="pages/text_image_content", verbose_name="image"
            ),
        ),
    ]
