# Generated by Django 4.1.2 on 2024-01-17 01:46

from django.db import migrations
import subject_imagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0046_alter_pagecontentboxitem_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontentboxitem",
            name="file",
            field=subject_imagefield.fields.SubjectImageField(
                blank=True,
                null=True,
                subject_location_field="subject_location",
                upload_to="pages/box_menu_content",
                verbose_name="image",
            ),
        ),
        migrations.DeleteModel(
            name="PageContentAttachment",
        ),
    ]
