# Generated by Django 4.1.2 on 2024-01-17 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0047_alter_pagecontentboxitem_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagecontentboxitem",
            options={
                "ordering": ("position",),
                "verbose_name": "Box",
                "verbose_name_plural": "Boxes",
            },
        ),
    ]
