# Generated by Django 4.1.2 on 2024-01-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0048_alter_pagecontentboxitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="caption",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="credits",
            field=models.TextField(blank=True, null=True, verbose_name="credits"),
        ),
        migrations.AddField(
            model_name="pagecontentboxmenu",
            name="show_captions",
            field=models.BooleanField(
                default=True,
                help_text="set to true if you want to show the captions of the boxes",
                verbose_name="show captions",
            ),
        ),
    ]
