# Generated by Django 4.1.2 on 2024-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0049_pagecontentboxitem_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="caption_en",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="caption_fr",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentboxitem",
            name="caption_it",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
    ]
