# Generated by Django 4.1.2 on 2024-01-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0050_pagecontentboxitem_caption_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecontentboxitem",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="pagecontentboxitem",
            name="caption_en",
        ),
        migrations.RemoveField(
            model_name="pagecontentboxitem",
            name="caption_fr",
        ),
        migrations.RemoveField(
            model_name="pagecontentboxitem",
            name="caption_it",
        ),
        migrations.RemoveField(
            model_name="pagecontentboxitem",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="pagecontentboxmenu",
            name="show_captions",
        ),
        migrations.AddField(
            model_name="pagecontentimage",
            name="caption",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentimage",
            name="caption_en",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentimage",
            name="caption_fr",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentimage",
            name="caption_it",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontentimage",
            name="credits",
            field=models.TextField(blank=True, null=True, verbose_name="credits"),
        ),
        migrations.AddField(
            model_name="pagecontentimage",
            name="show_captions",
            field=models.BooleanField(
                default=True,
                help_text="set to true if you want to show the captions of the images",
                verbose_name="show captions",
            ),
        ),
        migrations.AddField(
            model_name="pagecontentmultiimage",
            name="show_captions",
            field=models.BooleanField(
                default=True,
                help_text="set to true if you want to show the captions of the images",
                verbose_name="show captions",
            ),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="caption",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="caption_en",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="caption_fr",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="caption_it",
            field=models.TextField(blank=True, null=True, verbose_name="didascalia"),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="credits",
            field=models.TextField(blank=True, null=True, verbose_name="credits"),
        ),
        migrations.AddField(
            model_name="pagecontenttextimage",
            name="show_captions",
            field=models.BooleanField(
                default=True,
                help_text="set to true if you want to show the captions of the images",
                verbose_name="show captions",
            ),
        ),
    ]
