# Generated by Django 4.1.2 on 2024-01-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0052_remove_pagecontentmultiimageitem_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecontentmultiimageitem",
            name="height",
        ),
        migrations.AddField(
            model_name="pagecontentmultiimage",
            name="height",
            field=models.IntegerField(
                default=450,
                help_text="set the height of the image in pixels",
                verbose_name="height",
            ),
        ),
    ]
