# Generated by Django 4.1.2 on 2024-01-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0053_remove_pagecontentmultiimageitem_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontentmultiimage",
            name="height",
            field=models.IntegerField(
                default=450,
                help_text="set the max height of the carousel images in pixels",
                verbose_name="carousel max height",
            ),
        ),
    ]
