# Generated by Django 4.1.2 on 2024-01-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0054_alter_pagecontentmultiimage_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="transparent_admin",
            field=models.BooleanField(default=False, verbose_name="transparent admin"),
        ),
    ]
