# Generated by Django 4.1.2 on 2024-02-21 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0055_page_transparent_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagecontentimage",
            old_name="content",
            new_name="image_content",
        ),
    ]
