# Generated by Django 4.1.2 on 2024-02-21 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0056_rename_content_pagecontentimage_image_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagecontentmapitem",
            old_name="content_map",
            new_name="block",
        ),
    ]
