# Generated by Django 5.0.3 on 2024-03-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_rename_content_map_pagecontentmapitem_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='transparent_admin',
        ),
    ]
