# Generated by Django 5.0.3 on 2024-04-26 12:23

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_remove_page_transparent_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContentVideo',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.pagecontent')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='descrizione')),
                ('description_it', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='descrizione')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='descrizione')),
                ('description_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='descrizione')),
                ('credits', models.TextField(blank=True, null=True, verbose_name='credits')),
                ('platform', models.IntegerField(choices=[(1, 'Youtube'), (2, 'Vimeo'), (3, 'Twitch')], default=1, verbose_name='platform')),
                ('video_id', models.CharField(max_length=255, verbose_name='video id')),
                ('width_percent', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='width percent')),
            ],
            options={
                'verbose_name': 'Video block',
                'verbose_name_plural': 'Video blocks',
            },
            bases=('pages.pagecontent',),
        ),
    ]
