# Generated by Django 5.0.3 on 2024-05-22 14:20

import taggit_autosuggest.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_pagecontentvideo'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontentimage',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tag'),
        ),
    ]
