# Generated by Django 5.0.3 on 2024-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_pagecontentimage_url_alter_page_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontentimage',
            name='url',
            field=models.CharField(blank=True, null=True, verbose_name='url'),
        ),
    ]
