# Generated by Django 5.0.3 on 2024-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0061_alter_pagecontentimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontenttext',
            name='url',
            field=models.CharField(blank=True, null=True, verbose_name='url'),
        ),
    ]
