# Generated by Django 5.0.3 on 2024-05-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_thematicism_more_info_url'),
        ('pages', '0062_pagecontenttext_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='thematicisms',
            field=models.ManyToManyField(blank=True, related_name='pages', to='core.thematicism', verbose_name='tematismi'),
        ),
    ]
