# Generated by Django 5.0.3 on 2024-05-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_page_thematicisms'),
        ('places', '0012_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='pages', to='places.place', verbose_name='luoghi correlati'),
        ),
    ]
