# Generated by Django 5.0.3 on 2024-06-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_page_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='relevance',
            field=models.IntegerField(choices=[(1, 'alta'), (2, 'media'), (3, 'bassa')], default=2, help_text='priority level for searches', verbose_name='relevance'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_suggested',
            field=models.BooleanField(default=True, verbose_name='show suggested'),
        ),
    ]
