# Generated by Django 5.0.3 on 2024-06-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0065_page_relevance_page_show_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='relevance',
            field=models.IntegerField(choices=[(1, 'alta'), (2, 'media'), (3, 'bassa')], default=2, help_text='priority level for searches', verbose_name='rilevanza'),
        ),
    ]
